version: '3'

services:
    nginx:
        platform: linux/amd64
        restart: always
        depends_on:
            - api
            - client
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3000:80'
    api:
        platform: linux/amd64
        build:
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules
            - ./backend:/app
        env_file: ./backend/.env
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
